version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: tatou
      MYSQL_USER: tatou
      MYSQL_PASSWORD: tatou
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck: # 等数据库准备好
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  server:
    image: python:3.12-slim
    working_dir: /app
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONPATH: /app
      SECRET_KEY: dev-secret-change-me
      STORAGE_DIR: /app/storage
      TOKEN_TTL_SECONDS: "86400"
      DB_USER: group16
      DB_PASSWORD: BFa6q8P4HtiHprEDojDR
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: tatou

      RMAP_CLIENT_KEYS_DIR: /app/keys/clients
      RMAP_SERVER_PUBLIC: /app/keys/server_pub.asc # 你的文件就在 keys 根目录
      RMAP_SERVER_PRIVATE: /app/keys/server_priv.asc

      # 2025/10/3 11:02
      RMAP_DOC_ID: 17
      RMAP_METHOD: visible-text-redundant
      RMAP_POSITION: bottom-right
      WATERMARK_HMAC_KEY: rmap
      FLASK_ENV: development
      GUNICORN_CMD_ARGS: --workers 1 --log-level debug --capture-output --access-logfile - --error-logfile -

      # 2025/10/3 11:02

      # RMAP 输入的基准 PDF（容器内绝对路径，和 Documents.path 里保存的要一致）
      RMAP_INPUT_PDF: /app/storage/files/Group_16.pdf

    volumes:
      # 把你的代码挂进来（热更新）
      - ./server:/app/server
      # 把密钥目录整体挂进来（简单稳定），亦可保留你现在的“单文件挂载”，二选一即可
      - ./server/keys:/app/keys:ro
      # 关键：绑定宿主机 storage，而不是 named volume
      - ./storage:/app/storage
    command: >
      sh -c "pip install --no-cache-dir flask itsdangerous werkzeug sqlalchemy pymysql dill pymupdf pikepdf &&
             gunicorn -b 0.0.0.0:5000 server:app"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
