name: Mutation Testing

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # 每天凌晨3点自动跑一次全量

concurrency:
  group: mutation-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_MUTATE_PATHS: "server/src/"
  DEFAULT_TEST_RUNNER_QUICK: "pytest -q -k 'not slow'"
  DEFAULT_TEST_RUNNER_FULL: "pytest -q"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONHASHSEED: "0"

jobs:
  mutation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pytest mutmut

      - name: Show versions
        run: |
          python --version
          pytest --version
          python -m mutmut --version

      - name: Prepare test directories
        run: |
          mkdir -p keys/clients

      - name: Run baseline tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        working-directory: server
        run: |
          pytest -q

      - name: Run mutation tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python mutation_runner.py --paths server/src/ --tests server/test --timeout 60

      - name: Upload mutation report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mutmut-results
          path: |
            reports/
            mutmut.toml
          if-no-files-found: ignore
